# Generated by Django 4.1.7 on 2023-04-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='criterion number')),
                ('subnumber', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='criterion subnumber')),
                ('weight', models.FloatField(verbose_name='criterion weight')),
            ],
            options={
                'verbose_name': 'criterion',
                'verbose_name_plural': 'criterions',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='indicator name')),
                ('annotation', models.CharField(blank=True, max_length=500, verbose_name='indicator annotation')),
                ('privileged', models.BooleanField(default=False, verbose_name='indicator privileged status')),
            ],
            options={
                'verbose_name': 'indicator',
                'verbose_name_plural': 'indicators',
            },
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='type name')),
                ('datatype', models.CharField(choices=[('bool', 'boolean'), ('int', 'integer'), ('float', 'float'), ('str', 'text')], max_length=5, verbose_name='data type')),
            ],
            options={
                'verbose_name': 'value type',
                'verbose_name_plural': 'value types',
            },
        ),
        migrations.CreateModel(
            name='RatingPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='rating partition name')),
                ('abbreviation', models.CharField(max_length=5, unique=True, verbose_name='rating partition abbreviation')),
                ('indicators', models.ManyToManyField(related_name='partitions', through='rating.Criterion', to='rating.indicator', verbose_name='rating partition criterions')),
            ],
            options={
                'verbose_name': 'rating partition',
                'verbose_name_plural': 'rating partitions',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rating.valuetype', verbose_name='indicator value type'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.indicator', verbose_name='criterion indicator'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.ratingpartition', verbose_name='criterion partition'),
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('partition', 'number', 'subnumber')},
        ),
    ]
