# Generated by Django 4.2.1 on 2023-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='employee id'),
        ),
    ]
