# Generated by Django 4.1.7 on 2023-04-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='qualification name')),
            ],
            options={
                'verbose_name': 'qualification',
                'verbose_name_plural': 'qualifications',
            },
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='educator department')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educators.qualification', verbose_name='educator qualification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='educator profile')),
            ],
            options={
                'verbose_name': 'educator',
                'verbose_name_plural': 'educators',
            },
        ),
    ]
