# Generated by Django 4.2.1 on 2023-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='personal_number',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='personal number'),
            preserve_default=False,
        ),
    ]
