# Generated by Django 4.2.1 on 2023-06-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0003_educator_scopus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='scopus id'),
        ),
    ]
