# Generated by Django 4.2.1 on 2023-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0004_alter_educator_scopus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='wos_id',
            field=models.CharField(blank=True, max_length=13, verbose_name='Web of Science ID'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=11, verbose_name='Scopus ID'),
        ),
    ]
