# Generated by Django 4.2.1 on 2023-06-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0005_educator_wos_id_alter_educator_scopus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='personal_number',
        ),
    ]
